### ISSUE TITLE
Self sent messages won't display on non-Pidgin clients

### ISSUE THREAD

**Issue by EionRobb** [majn/telegram-purple#382]
Clients such as Adium or bitlbee won't display self-sent messages from other devices in group chats.  This is due to how the `PURPLE_MESSAGE_SEND` flag is handled, that its not possible to know whether a message was sent from the same device as where libpurple is running or whether it's from a different one.

A new `PURPLE_MESSAGE_` flag was added in 2.12.0 to support this, [`PURPLE_MESSAGE_REMOTE_SEND`](https://bitbucket.org/pidgin/main/src/3de750fbe725928279fdcd5bc8945fe068e0f5cb/libpurple/conversation.h?at=release-2.x.y&fileviewer=file-view-default#conversation.h-130)

This flag is supported in recent versions of bitlbee, but not Adium (or other clients) yet.  Instead, they look for the `PURPLE_MESSAGE_DELAYED` flag.

Consider adding flags for both `PURPLE_MESSAGE_DELAYED` and `PURPLE_MESSAGE_REMOTE_SEND` when displaying self-sent messages in a group chat.

**Comment by dequis** [comment]
So I was looking into this because it turns out no self-messages work in bitlbee, not even private ones (you can mark #427 as a dupe of this). Sadly this isn't as easy as adding some flag.

For private messages the mechanism may be slightly different to `PURPLE_MESSAGE_REMOTE_SEND` but the concept is the same, just signal that this message is displayable and not an echo of something the user wrote locally. The problem is that all local and remote self-messages in telegram look the same.

Attached [four backtraces for each situation](https://github.com/majn/telegram-purple/files/1826826/backtraces.txt). That was going to be part of this comment but it's verbose and redundant, just shows that all types of messages, even those written from pidgin, are actually displayed when received back from the server.

I don't know, is there a reasonable way to flag only messages written by clients other than ours?

**Comment by BenWiederhake** [comment]
Should be fixed by [v1.4.2](https://github.com/majn/telegram-purple/releases/tag/v1.4.2), specifically 38d6ac23043ab4344f0f2b3fbba9169de4a22891, credit goes to @himselfv.  Feel free to reopen if it doesn't work.

**Comment by dequis** [comment]
That doesn't seem to be using PURPLE_MESSAGE_REMOTE_SEND at all though

**Comment by BenWiederhake** [comment]
You're right, my fault.

PRs welcome.

**Comment by dequis** [comment]
I still don't really know how to determine that this flag should be set, AFAIK tgp_our_msg() returns true for both messages sent from this instance and messages sent from remote instances.

And I don't really understand what is being improved by the linked commit - extending the existing flags to encrypted chats i guess?

**Comment by dequis** [comment]
Actually reading my older comments here, this may have fixed the problem for groupchats (but not for private messages), need to run it and test

**Comment by arcadedroid** [comment]
I just tested this, I don't see my own messages on Bitlbee.

**Comment by dequis** [comment]
In groupchats or private messages? The latter didn't change at all.

**Comment by arcadedroid** [comment]
Group chats.

**Comment by BenWiederhake** [comment]
If anyone feels like implementing this enhancement, it might be a better idea to direct your energy to [tdlib-purple](https://github.com/ars3niy/tdlib-purple), which might already have this enhancement. For now, there seems to be nobody who implements any enhancements for telegram-purple, so I'm closing all "enhancement" issues.

Didn't someone say that it's just about adding `PURPLE_MESSAGE_REMOTE_SEND` somewhere?

**Comment by dequis** [comment]
> Didn't someone say that it's just about adding `PURPLE_MESSAGE_REMOTE_SEND` somewhere?

Yeah but with the way telegram-purple is written and routes messages internally, that's non-trivial
